insert into estoquepurchase.categorias values (1, 'SEM CATEGORIA');
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Canelados",	"99.9"	,1	,sysdate(),	sysdate(),	"1"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos Longos",	"119.9"	,1	,sysdate(),	sysdate(),	"2"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos Promoção",	"79.9"	,1	,sysdate(),	sysdate(),	"3"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Purpurina",	"149.9"	,1	,sysdate(),	sysdate(),	"4"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Purpurina Preto",	"329.9"	,1	,sysdate(),	sysdate(),	"5"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Shorts Lady Rock",	"119.9"	,1	,sysdate(),	sysdate(),	"6"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Shorts Fillger Jeans",	"79.9"	,1	,sysdate(),	sysdate(),	"7"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Shorts Promo",	"39.9"	,1	,sysdate(),	sysdate(),	"8"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Purpurina Teresina",	"229.9"	,1	,sysdate(),	sysdate(),	"9"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Bahamas",	"169.9"	,1	,sysdate(),	sysdate(),	"10"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Gramado",	"229.9"	,1	,sysdate(),	sysdate(),	"11"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Lily Miami",	"259.9"	,1	,sysdate(),	sysdate(),	"12"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Caribe",	"259.9"	,1	,sysdate(),	sysdate(),	"13"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Bandagem",	"79.9"	,1	,sysdate(),	sysdate(),	"14"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calças Lady Rock",	"99.9"	,1	,sysdate(),	sysdate(),	"15"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Lily",	"77.9"	,1	,sysdate(),	sysdate(),	"16"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys Pretos #",	"89.9"	,1	,sysdate(),	sysdate(),	"17"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saias Corino",	"59.9"	,1	,sysdate(),	sysdate(),	"18"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Branco",	"109.9"	,1	,sysdate(),	sysdate(),	"19"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Branco",	"39.9"	,1	,sysdate(),	sysdate(),	"20"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Trançado Branco",	"69.9"	,1	,sysdate(),	sysdate(),	"21"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Sutiãs",	"39.9"	,1	,sysdate(),	sysdate(),	"22"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Trico",	"59.9"	,1	,sysdate(),	sysdate(),	"23"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Meias Arrastão",	"39.9"	,1	,sysdate(),	sysdate(),	"24"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys Arrastao Promo",	"29.9"	,1	,sysdate(),	sysdate(),	"25"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Colan Manga",	"29.9"	,1	,sysdate(),	sysdate(),	"26"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Purpurina Kilye",	"79.9"	,1	,sysdate(),	sysdate(),	"27"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Colete",	"99.9"	,1	,sysdate(),	sysdate(),	"28"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Moleton",	"89.9"	,1	,sysdate(),	sysdate(),	"29"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Casaquinho",	"109.9"	,1	,sysdate(),	sysdate(),	"30"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Mid",	"59.9"	,1	,sysdate(),	sysdate(),	"31"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Peças Promo",	"19.9"	,1	,sysdate(),	sysdate(),	"32"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calças Iso Jeans",	"29.9"	,1	,sysdate(),	sysdate(),	"33"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquinis",	"99.9"	,1	,sysdate(),	sysdate(),	"34"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Jaqueta Jeans",	"59.9"	,1	,sysdate(),	sysdate(),	"35"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Jaqueta Sintética",	"69.9"	,1	,sysdate(),	sysdate(),	"36"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquinis Avulsos",	"19.9"	,1	,sysdate(),	sysdate(),	"37"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Renda Preto",	"69.9"	,1	,sysdate(),	sysdate(),	"38"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Renda Branco",	"69.9"	,1	,sysdate(),	sysdate(),	"39"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Gola Liso",	"59.9"	,1	,sysdate(),	sysdate(),	"40"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Preto",	"109.9"	,1	,sysdate(),	sysdate(),	"41"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Tule",	"99.9"	,1	,sysdate(),	sysdate(),	"42"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Tule Camisetão",	"99.9"	,1	,sysdate(),	sysdate(),	"43"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Blusa Ciganinha",	"59.9"	,1	,sysdate(),	sysdate(),	"44"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Croppped Suplex Div",	"49.9"	,1	,sysdate(),	sysdate(),	"45"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Bergaline",	"99.9"	,1	,sysdate(),	sysdate(),	"46"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Ombro Suplex",	"79.9"	,1	,sysdate(),	sysdate(),	"47"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Bandage",	"59.9"	,1	,sysdate(),	sysdate(),	"48"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Suplex",	"59.9"	,1	,sysdate(),	sysdate(),	"49"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Renda Festa",	"49.9"	,1	,sysdate(),	sysdate(),	"50"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Suplex Branco Laço",	"79.9"	,1	,sysdate(),	sysdate(),	"51"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Alça Renda",	"89.9"	,1	,sysdate(),	sysdate(),	"52"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Renda Verao",	"99.9"	,1	,sysdate(),	sysdate(),	"53"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Transado Ilhos 🚨🚨🚨🚨",	"119.9"	,1	,sysdate(),	sysdate(),	"54"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Regata Pedraria",	"59.9"	,1	,sysdate(),	sysdate(),	"55"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Social",	"89.9"	,1	,sysdate(),	sysdate(),	"56"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Blusas Alcinha",	"49.9"	,1	,sysdate(),	sysdate(),	"57"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Camisa Tule",	"99.9"	,1	,sysdate(),	sysdate(),	"58"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia De Cirre",	"89.9"	,1	,sysdate(),	sysdate(),	"59"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Tule Duplo",	"99.9"	,1	,sysdate(),	sysdate(),	"60"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia De Cirre Ilhos",	"89.9"	,1	,sysdate(),	sysdate(),	"61"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys Abertos",	"99.9"	,1	,sysdate(),	sysdate(),	"62"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ciganinha Verão Cinza",	"69.9"	,1	,sysdate(),	sysdate(),	"63"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Maxi Colete",	"119.9"	,1	,sysdate(),	sysdate(),	"64"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped De Tule",	"59.9"	,1	,sysdate(),	sysdate(),	"65"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Choker Canelado",	"99.9"	,1	,sysdate(),	sysdate(),	"66"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Basico Alcinha",	"79.9"	,1	,sysdate(),	sysdate(),	"67"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos Cinza Suplex",	"69.9"	,1	,sysdate(),	sysdate(),	"68"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Babado Claro",	"59.9"	,1	,sysdate(),	sysdate(),	"69"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Renda 2 Alça Fina",	"69.9"	,1	,sysdate(),	sysdate(),	"70"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Renda 3 Alça Grossa",	"69.9"	,1	,sysdate(),	sysdate(),	"71"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Fashion",	"89.9"	,1	,sysdate(),	sysdate(),	"72"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Cinza Vazado",	"79.9"	,1	,sysdate(),	sysdate(),	"73"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Preto Vazado",	"79.9"	,1	,sysdate(),	sysdate(),	"74"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Blusa De Ilhos",	"49.9"	,1	,sysdate(),	sysdate(),	"75"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido De Ilhos",	"79.9"	,1	,sysdate(),	sysdate(),	"76"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ombro A Ombro Branco",	"0"	,1	,sysdate(),	sysdate(),	"77"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça California Purpurina",	"0"	,1	,sysdate(),	sysdate(),	"78"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Suplex Vazada",	"69.9"	,1	,sysdate(),	sysdate(),	"79"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Canelado Colorido",	"59.9"	,1	,sysdate(),	sysdate(),	"80"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Napolitano Preto E Branco",	"69.9"	,1	,sysdate(),	sysdate(),	"81"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Preto Liso Aberto Costa",	"89.9"	,1	,sysdate(),	sysdate(),	"82"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Florido",	"69.9"	,1	,sysdate(),	sysdate(),	"83"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Transparente Preto",	"69.9"	,1	,sysdate(),	sysdate(),	"84"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Napolitano",	"59.9"	,1	,sysdate(),	sysdate(),	"85"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Canelado De Botões",	"59.9"	,1	,sysdate(),	sysdate(),	"86"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos Canelado Ajustados",	"69.9"	,1	,sysdate(),	sysdate(),	"87"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Óculos",	"49.9"	,1	,sysdate(),	sysdate(),	"88"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cintos",	"59.9"	,1	,sysdate(),	sysdate(),	"89"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Tule Camisetão Gg",	"109.9"	,1	,sysdate(),	sysdate(),	"90"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Azul 226 34",	"109.9"	,1	,sysdate(),	sysdate(),	"91"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Azul 226 36",	"109.9"	,1	,sysdate(),	sysdate(),	"92"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Azul 226 38",	"109.9"	,1	,sysdate(),	sysdate(),	"93"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Azul 226 40",	"109.9"	,1	,sysdate(),	sysdate(),	"94"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Azul 226 42",	"109.9"	,1	,sysdate(),	sysdate(),	"95"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Azul 226 44",	"109.9"	,1	,sysdate(),	sysdate(),	"96"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Branco 04 34",	"109.9"	,1	,sysdate(),	sysdate(),	"97"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Branco 04 36",	"109.9"	,1	,sysdate(),	sysdate(),	"98"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Branco 04 38",	"109.9"	,1	,sysdate(),	sysdate(),	"99"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Branco 04 40",	"109.9"	,1	,sysdate(),	sysdate(),	"100"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Branco 04 42",	"109.9"	,1	,sysdate(),	sysdate(),	"101"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Branco 04 44",	"109.9"	,1	,sysdate(),	sysdate(),	"102"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Preto 02 34",	"109.9"	,1	,sysdate(),	sysdate(),	"103"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Preto 02 36",	"109.9"	,1	,sysdate(),	sysdate(),	"104"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Preto 02 38",	"109.9"	,1	,sysdate(),	sysdate(),	"105"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Preto 02 40",	"109.9"	,1	,sysdate(),	sysdate(),	"106"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Preto 02 42",	"109.9"	,1	,sysdate(),	sysdate(),	"107"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Carmen Preto 02 44",	"109.9"	,1	,sysdate(),	sysdate(),	"108"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Ombro A Ombro Vermelho Listrado Canelado",	"89.9"	,1	,sysdate(),	sysdate(),	"109"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Ombro A Ombro Branco Listrado Canelado",	"89.9"	,1	,sysdate(),	sysdate(),	"110"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Ombro A Ombro Preto Listrado Canelado",	"89.9"	,1	,sysdate(),	sysdate(),	"111"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Rosa Bebe",	"89.9"	,1	,sysdate(),	sysdate(),	"112"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Rosa Forte",	"89.9"	,1	,sysdate(),	sysdate(),	"113"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Azul",	"89.9"	,1	,sysdate(),	sysdate(),	"114"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Preto",	"89.9"	,1	,sysdate(),	sysdate(),	"115"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Estampa Floral Fundo Preto",	"89.9"	,1	,sysdate(),	sysdate(),	"116"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Estampa Floral Fundo Azul Marinho",	"89.9"	,1	,sysdate(),	sysdate(),	"117"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys/Maiô Estampada Preto E Branco Flor",	"89.9"	,1	,sysdate(),	sysdate(),	"118"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys/Maiô Estampada Blue Azul Zigzag",	"89.9"	,1	,sysdate(),	sysdate(),	"119"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys/Maiô Estampada Rosa Zigzag",	"89.9"	,1	,sysdate(),	sysdate(),	"120"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys/Maiô Estampada Colors Preto",	"89.9"	,1	,sysdate(),	sysdate(),	"121"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys/Maiô Estampada Penas Verde",	"89.9"	,1	,sysdate(),	sysdate(),	"122"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bodys/Maiô Estampada Caribe Flores Rosa Branco",	"89.9"	,1	,sysdate(),	sysdate(),	"123"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Blusinha Listrada Babado",	"79.9"	,1	,sysdate(),	sysdate(),	"124"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Love Arrastão",	"69.9"	,1	,sysdate(),	sysdate(),	"125"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Aberto Nó Listrado",	"109.9"	,1	,sysdate(),	sysdate(),	"126"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Aberto Nó Todo Preto",	"109.9"	,1	,sysdate(),	sysdate(),	"127"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Alcinha Cinza Mecla Canelado",	"79.9"	,1	,sysdate(),	sysdate(),	"128"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Napolitano Preto Branco Rosa",	"89.9"	,1	,sysdate(),	sysdate(),	"129"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos X Canelados Marsala",	"79.9"	,1	,sysdate(),	sysdate(),	"130"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos X Canelados Cinza",	"79.9"	,1	,sysdate(),	sysdate(),	"131"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestidos X Canelados Preto",	"79.9"	,1	,sysdate(),	sysdate(),	"132"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusa Rosa Amarra",	"69.9"	,1	,sysdate(),	sysdate(),	"133"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusa Preto Amarra",	"69.9"	,1	,sysdate(),	sysdate(),	"134"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bolsa Branca Chanel",	"109.9"	,1	,sysdate(),	sysdate(),	"135"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bolsa Marrom Pequena Chanel",	"79.9"	,1	,sysdate(),	sysdate(),	"136"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bolsa Preta Pequena",	"79.9"	,1	,sysdate(),	sysdate(),	"137"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Camuflada Preta E Cinza",	"149.9"	,1	,sysdate(),	sysdate(),	"138"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Off Saia Envelope Mk Fashoin",	"149.9"	,1	,sysdate(),	sysdate(),	"169"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Listrado Vertical",	"89.9"	,1	,sysdate(),	sysdate(),	"139"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Abacaxi",	"89.9"	,1	,sysdate(),	sysdate(),	"140"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flamingo Fundo Preto",	"89.9"	,1	,sysdate(),	sysdate(),	"141"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Preto Básico Aberto Nas Costas",	"89.9"	,1	,sysdate(),	sysdate(),	"142"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Poliamida",	"89.9"	,1	,sysdate(),	sysdate(),	"143"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Sutiã Preto Com Tule",	"65"	,1	,sysdate(),	sysdate(),	"144"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Calcinha Preto Com Tira",	"75"	,1	,sysdate(),	sysdate(),	"145"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Calcinha Veludo Molhado Bordô",	"70"	,1	,sysdate(),	sysdate(),	"146"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Sutiã Veludo Molhado Bordô",	"70"	,1	,sysdate(),	sysdate(),	"147"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Calcinha Rosa Ripple",	"70"	,1	,sysdate(),	sysdate(),	"148"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Sutiã Rosa Ripple",	"70"	,1	,sysdate(),	sysdate(),	"149"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Calcinha Pink Babado",	"70"	,1	,sysdate(),	sysdate(),	"150"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Sutiã Pink Babado",	"70"	,1	,sysdate(),	sysdate(),	"151"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Calcinha Preto Borda Rosa Ripple",	"75"	,1	,sysdate(),	sysdate(),	"152"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Sutiã Pink Preto Borda Rosa Ripple",	"75"	,1	,sysdate(),	sysdate(),	"153"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ciganinha Verão Preto",	"69.9"	,1	,sysdate(),	sysdate(),	"154"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ciganinha Verão Pink",	"69.9"	,1	,sysdate(),	sysdate(),	"155"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ciganinha Verão Rose Flozinhas",	"69.9"	,1	,sysdate(),	sysdate(),	"156"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ciganinha Verão Listras Azuis Com Flores",	"69.9"	,1	,sysdate(),	sysdate(),	"157"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Alcinha Marsala Canelado",	"79.9"	,1	,sysdate(),	sysdate(),	"158"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Alcinha Preto Canelado",	"79.9"	,1	,sysdate(),	sysdate(),	"159"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Canelado Nó Alcinha Marsala",	"89.9"	,1	,sysdate(),	sysdate(),	"160"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Canelado Nó Alcinha Preto",	"89.9"	,1	,sysdate(),	sysdate(),	"161"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Canelado Nó Alcinha Cinza",	"89.9"	,1	,sysdate(),	sysdate(),	"162"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Canelado Nó Alcinha Salmão",	"89.9"	,1	,sysdate(),	sysdate(),	"163"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Canelada Com Fenda Preta",	"79.9"	,1	,sysdate(),	sysdate(),	"164"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Canelada Com Fenda Bordô",	"79.9"	,1	,sysdate(),	sysdate(),	"165"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cinto Grosso Preto Dupla Fivela Prata",	"79.9"	,1	,sysdate(),	sysdate(),	"166"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cinto Fino Preto Dupla Fivela Prata",	"69.9"	,1	,sysdate(),	sysdate(),	"167"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cinto Fino Branco Dupla Fivela Prata",	"59.9"	,1	,sysdate(),	sysdate(),	"168"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Longo Renda Mk Fashion Branco",	"189.9"	,1	,sysdate(),	sysdate(),	"170"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Longo Renda Mk Fashion Preto",	"189.9"	,1	,sysdate(),	sysdate(),	"171"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Colares",	"19.90"	,1	,sysdate(),	sysdate(),	"172"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Choker",	"29.90"	,1	,sysdate(),	sysdate(),	"173"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bolsa De Concha",	"109.90"	,1	,sysdate(),	sysdate(),	"174"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Argola Estampado Floral Verde",	"69.90"	,1	,sysdate(),	sysdate(),	"175"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Argola Rose Liso",	"69.90"	,1	,sysdate(),	sysdate(),	"176"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Argola Preto Liso",	"69.90"	,1	,sysdate(),	sysdate(),	"177"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Amarrar Na Frente Preto Liso",	"69.90"	,1	,sysdate(),	sysdate(),	"178"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Pantacourt Branca Com Listras Aberta Nos Lados",	"119.90"	,1	,sysdate(),	sysdate(),	"179"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Envelope Branca",	"119.90"	,1	,sysdate(),	sysdate(),	"180"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Envelope Preta",	"119.90"	,1	,sysdate(),	sysdate(),	"181"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Preto 36",	"109.90"	,1	,sysdate(),	sysdate(),	"182"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Branco 34",	"109.90"	,1	,sysdate(),	sysdate(),	"183"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Branco 36",	"109.90"	,1	,sysdate(),	sysdate(),	"184"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Branco 38",	"109.90"	,1	,sysdate(),	sysdate(),	"185"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Branco 40",	"109.90"	,1	,sysdate(),	sysdate(),	"186"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Azul Claro 34",	"109.90"	,1	,sysdate(),	sysdate(),	"187"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Azul Claro 36",	"109.90"	,1	,sysdate(),	sysdate(),	"188"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Azul Claro 38",	"109.90"	,1	,sysdate(),	sysdate(),	"189"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Azul Manchado 34",	"109.90"	,1	,sysdate(),	sysdate(),	"190"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Azul Manchado 36",	"109.90"	,1	,sysdate(),	sysdate(),	"191"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Tubinho Branco",	"89.90"	,1	,sysdate(),	sysdate(),	"192"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Tubinho Rose",	"89.90"	,1	,sysdate(),	sysdate(),	"193"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Tubinho Marsala",	"89.90"	,1	,sysdate(),	sysdate(),	"194"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Conjuntinhos Napolitanos Cropped",	"69.90"	,1	,sysdate(),	sysdate(),	"195"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Conjuntinhos Napolitanos Saia",	"79.90"	,1	,sysdate(),	sysdate(),	"196"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Conjuntinho De Renda Branco",	"149.90"	,1	,sysdate(),	sysdate(),	"197"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Tule Estampado De Flor",	"59.90"	,1	,sysdate(),	sysdate(),	"198"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Camisa Adidas Rosa",	"49.90"	,1	,sysdate(),	sysdate(),	"199"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Camisa Adidas Branca",	"49.90"	,1	,sysdate(),	sysdate(),	"200"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Choker",	"29.90"	,1	,sysdate(),	sysdate(),	"201"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Menina Cheirosa Branco 38",	"109.90"	,1	,sysdate(),	sysdate(),	"202"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Amarrar Viscose Branco",	"119.90"	,1	,sysdate(),	sysdate(),	"203"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Amarrar Viscose Preto",	"119.90"	,1	,sysdate(),	sysdate(),	"204"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Marsala",	"89.90"	,1	,sysdate(),	sysdate(),	"205"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Flores Coloridas Fundo Preto",	"89.90"	,1	,sysdate(),	sysdate(),	"206"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Branco",	"89.99"	,1	,sysdate(),	sysdate(),	"207"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Azul Turquesa Floral",	"69.90"	,1	,sysdate(),	sysdate(),	"208"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Ciganinha Branco",	"59.90"	,1	,sysdate(),	sysdate(),	"209"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Envelope Comprida Azul Floral",	"119.90"	,1	,sysdate(),	sysdate(),	"210"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Envelope Comprida Preta Lisa",	"119.90"	,1	,sysdate(),	sysdate(),	"211"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Em Cima Preto Liso Fru Fru P",	"75.00"	,1	,sysdate(),	sysdate(),	"212A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Liso Fru Fru P",	"75.00"	,1	,sysdate(),	sysdate(),	"212B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Liso Fru Fru P",	"129.90"	,1	,sysdate(),	sysdate(),	"212C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Em Cima Preto Liso Fru Fru M",	"75.00"	,1	,sysdate(),	sysdate(),	"213A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Liso Fru Fru M",	"75.00"	,1	,sysdate(),	sysdate(),	"213B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Liso Fru Fru M",	"129.90"	,1	,sysdate(),	sysdate(),	"213C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Etnico M",	"75.00"	,1	,sysdate(),	sysdate(),	"214A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Etnico M",	"75.00"	,1	,sysdate(),	sysdate(),	"214B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Etnico M",	"129.90"	,1	,sysdate(),	sysdate(),	"214C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"215A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"215B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Etnico G",	"129.90"	,1	,sysdate(),	sysdate(),	"215C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Pink Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"216A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Pink Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"216B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Pink Etnico G",	"129.90"	,1	,sysdate(),	sysdate(),	"216C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Liso Tomara Que Caia P",	"75.00"	,1	,sysdate(),	sysdate(),	"217A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Etnico C/Tiras P",	"75.00"	,1	,sysdate(),	sysdate(),	"217B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Liso Etnico P",	"129.90"	,1	,sysdate(),	sysdate(),	"217C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Liso Tomara Que Caia M",	"75.00"	,1	,sysdate(),	sysdate(),	"218A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Etnico C/Tiras M",	"75.00"	,1	,sysdate(),	sysdate(),	"218B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Liso Etnico M",	"129.90"	,1	,sysdate(),	sysdate(),	"218C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Liso Tomara Que Caia G",	"75.00"	,1	,sysdate(),	sysdate(),	"219A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Liso Etnico C/Tiras G",	"75.00"	,1	,sysdate(),	sysdate(),	"219B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Liso Etinco G",	"129.90"	,1	,sysdate(),	sysdate(),	"219C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Liso Tomara Que Caia P",	"75.00"	,1	,sysdate(),	sysdate(),	"220A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Etnico C/Tiras P",	"75.00"	,1	,sysdate(),	sysdate(),	"220B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Liso Etnico P",	"129.90"	,1	,sysdate(),	sysdate(),	"220C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Liso Tomara Que Caia M",	"75.00"	,1	,sysdate(),	sysdate(),	"221A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Etnico C/Tiras M",	"75.00"	,1	,sysdate(),	sysdate(),	"221B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Liso Etnico M",	"129.90"	,1	,sysdate(),	sysdate(),	"221C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Liso Etnico Tomaraque Caia G",	"75.00"	,1	,sysdate(),	sysdate(),	"222A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Etnico C/Tiras G",	"75.00"	,1	,sysdate(),	sysdate(),	"222B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Liso Etnico G",	"129.90"	,1	,sysdate(),	sysdate(),	"222C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Salmao Vazado G",	"75.00"	,1	,sysdate(),	sysdate(),	"223A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Salmao Vazado G",	"75.00"	,1	,sysdate(),	sysdate(),	"223B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Salmao Vazado G",	"129.90"	,1	,sysdate(),	sysdate(),	"223C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Branco Vazado Ano Novo",	"75.00"	,1	,sysdate(),	sysdate(),	"224A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Branco Vazado Ano Novo",	"75.00"	,1	,sysdate(),	sysdate(),	"224B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Branco Vazado Ano Novo",	"129.90"	,1	,sysdate(),	sysdate(),	"224C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Azul Turquesa Vazado",	"75.00"	,1	,sysdate(),	sysdate(),	"225A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Azul Turquesa Vazado",	"75.00"	,1	,sysdate(),	sysdate(),	"225B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Azul Turquesa Vazado",	"129.90"	,1	,sysdate(),	sysdate(),	"225C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Branco Floral C/Tela P",	"75.00"	,1	,sysdate(),	sysdate(),	"226A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Branco Floral C/Tela P",	"75.00"	,1	,sysdate(),	sysdate(),	"226B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Branco Floral C/Tela P",	"129.90"	,1	,sysdate(),	sysdate(),	"226C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Floral P",	"75.00"	,1	,sysdate(),	sysdate(),	"227A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Floral P",	"75.00"	,1	,sysdate(),	sysdate(),	"227B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Floral P",	"129.90"	,1	,sysdate(),	sysdate(),	"227C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Vazado P",	"75.00"	,1	,sysdate(),	sysdate(),	"228A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Vazado P",	"75.00"	,1	,sysdate(),	sysdate(),	"228B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Vazado P",	"129.90"	,1	,sysdate(),	sysdate(),	"228C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Verde Militar P",	"75.00"	,1	,sysdate(),	sysdate(),	"229A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Verde Militar P",	"75.00"	,1	,sysdate(),	sysdate(),	"229B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Verde Militar P",	"129.90"	,1	,sysdate(),	sysdate(),	"229C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Verde Militar M",	"75.00"	,1	,sysdate(),	sysdate(),	"230A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Verde Militar M",	"75.00"	,1	,sysdate(),	sysdate(),	"230B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Verde Militar M",	"129.90"	,1	,sysdate(),	sysdate(),	"230C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Verde Militar Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"231A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Verde Militar Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"231B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Verde Militar Gg",	"129.90"	,1	,sysdate(),	sysdate(),	"231C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Flor Bordado P",	"75.00"	,1	,sysdate(),	sysdate(),	"232A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Flor C/Tiras P",	"75.00"	,1	,sysdate(),	sysdate(),	"232B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Flor Bordado P",	"129.90"	,1	,sysdate(),	sysdate(),	"232C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Flor Bordado P",	"75.00"	,1	,sysdate(),	sysdate(),	"233A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Flor C/Tiras P",	"75.00"	,1	,sysdate(),	sysdate(),	"233B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Flor Bordado P",	"129.90"	,1	,sysdate(),	sysdate(),	"233C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Flor Bordado G",	"75.00"	,1	,sysdate(),	sysdate(),	"234A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Flor Bordado G",	"75.00"	,1	,sysdate(),	sysdate(),	"234B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Flor Bordado G",	"129.90"	,1	,sysdate(),	sysdate(),	"234C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Blue M",	"75.00"	,1	,sysdate(),	sysdate(),	"235A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Blue M",	"75.00"	,1	,sysdate(),	sysdate(),	"235B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Blue M",	"129.90"	,1	,sysdate(),	sysdate(),	"235C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Fundo Bordo Folhas P",	"75.00"	,1	,sysdate(),	sysdate(),	"236A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Fundo Bordo Folhas P",	"75.00"	,1	,sysdate(),	sysdate(),	"236B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Fundo Bordo Folhas P",	"129.90"	,1	,sysdate(),	sysdate(),	"236C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Fundo Bordo Folhas M",	"75.00"	,1	,sysdate(),	sysdate(),	"237A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Fundo Bordo Folhas M",	"75.00"	,1	,sysdate(),	sysdate(),	"237B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Fundo Bordo Folhas M",	"129.90"	,1	,sysdate(),	sysdate(),	"237C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Branco Fundo Listrado G",	"75.00"	,1	,sysdate(),	sysdate(),	"238A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Branco Fundo Listrado G",	"75.00"	,1	,sysdate(),	sysdate(),	"238B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Branco Fundo Listrado G",	"129.90"	,1	,sysdate(),	sysdate(),	"238C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Branco Fundo Listrado",	"75.00"	,1	,sysdate(),	sysdate(),	"239A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Branco Fundo Listrado",	"75.00"	,1	,sysdate(),	sysdate(),	"239B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Branco Fundo Listrado",	"129.90"	,1	,sysdate(),	sysdate(),	"239C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Preto Escama Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"240A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Escama Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"240B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Preto Escama Gg",	"129.90"	,1	,sysdate(),	sysdate(),	"240C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Pink Escama Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"241A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Pink Escama Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"241B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Pink Escama Gg",	"129.90"	,1	,sysdate(),	sysdate(),	"241C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Vermelho Escama Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"242A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Vermelho Escama Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"242B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Vermelho Escama Gg",	"129.90"	,1	,sysdate(),	sysdate(),	"242C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Listras Rosa Mix Flores Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"243A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Listras Rosa Mix Flores Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"243B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Listras Rosa Mix Flores Gg",	"129.90"	,1	,sysdate(),	sysdate(),	"243C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquiini Emcima Listras Azul Mix Flores",	"75.00"	,1	,sysdate(),	sysdate(),	"244A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixolistras Azul Mix Flores",	"75.00"	,1	,sysdate(),	sysdate(),	"244B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Listras Azul Flores",	"129.90"	,1	,sysdate(),	sysdate(),	"244C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Listras Preta Mix Flores",	"75.00"	,1	,sysdate(),	sysdate(),	"245A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Listras Pretamix Flores",	"75.00"	,1	,sysdate(),	sysdate(),	"245B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Listras Preta Mix Flores",	"129.90"	,1	,sysdate(),	sysdate(),	"245C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Azul Fundo Verde Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"246A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Azul Fundo Verde Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"246B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Azul Fundo Verde Etnico G",	"129.90"	,1	,sysdate(),	sysdate(),	"246C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Verde Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"247A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Verde Etnico G",	"75.00"	,1	,sysdate(),	sysdate(),	"247B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Verde Etnico G",	"129.90"	,1	,sysdate(),	sysdate(),	"247C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Bordado Colorido G",	"75.00"	,1	,sysdate(),	sysdate(),	"248A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Bordado Colorido G",	"75.00"	,1	,sysdate(),	sysdate(),	"248B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Bordado Colorido G",	"129.90"	,1	,sysdate(),	sysdate(),	"248C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Pink Liso G",	"75.00"	,1	,sysdate(),	sysdate(),	"249A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Pink C/Tira Dupla G",	"75.00"	,1	,sysdate(),	sysdate(),	"249B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Pink Liso G",	"129.90"	,1	,sysdate(),	sysdate(),	"249C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Rosa Tira Preta Vazada G",	"75.00"	,1	,sysdate(),	sysdate(),	"250A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Rosa Tira Preta Vazada P",	"75.00"	,1	,sysdate(),	sysdate(),	"250B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Tira Preta Vazada G-P",	"129.90"	,1	,sysdate(),	sysdate(),	"250C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Branco Ergometrico P",	"75.00"	,1	,sysdate(),	sysdate(),	"251A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Preto Liso S/Tiras P",	"75.00"	,1	,sysdate(),	sysdate(),	"251B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Branco Ergometrico E Preto P",	"129.90"	,1	,sysdate(),	sysdate(),	"251C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Ergometrico Preto G",	"75.00"	,1	,sysdate(),	sysdate(),	"252A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Ergometrico Preto G",	"75.00"	,1	,sysdate(),	sysdate(),	"252B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Ergometrico Preto G",	"129.90"	,1	,sysdate(),	sysdate(),	"252C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Croche P",	"75.00"	,1	,sysdate(),	sysdate(),	"253A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Croche P",	"75.00"	,1	,sysdate(),	sysdate(),	"253B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Croche P",	"129.90"	,1	,sysdate(),	sysdate(),	"253C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Croche M",	"75.00"	,1	,sysdate(),	sysdate(),	"254A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Croche M",	"75.00"	,1	,sysdate(),	sysdate(),	"254B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Croche M",	"129.90"	,1	,sysdate(),	sysdate(),	"254C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Salmao De Pingente P/38",	"75.00"	,1	,sysdate(),	sysdate(),	"255A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquni Embaixo Salmão Etnico P/38",	"75.00"	,1	,sysdate(),	sysdate(),	"255B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Salmão Etnico P/38",	"129.90"	,1	,sysdate(),	sysdate(),	"255C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flores Redondos Colorido",	"79.90"	,1	,sysdate(),	sysdate(),	"256"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flores Listradinho Azul",	"79.90"	,1	,sysdate(),	sysdate(),	"257"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flores Listradinho Rosa Bebe",	"79.90"	,1	,sysdate(),	sysdate(),	"258"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Zigzap Preto Branco",	"79.90"	,1	,sysdate(),	sysdate(),	"259"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flores Listradopreto Horizontal",	"79.90"	,1	,sysdate(),	sysdate(),	"260"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flores Brancas Rose",	"79.90"	,1	,sysdate(),	sysdate(),	"261"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Preto Corda Decote E Aberto Cintura",	"79.90"	,1	,sysdate(),	sysdate(),	"262"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Fundo Branco Palmeiras",	"79.90"	,1	,sysdate(),	sysdate(),	"263"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Fundo Azul Mix Flores",	"79.90"	,1	,sysdate(),	sysdate(),	"264"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Fundo Branco Flores Vermelho Verde",	"79.90"	,1	,sysdate(),	sysdate(),	"265"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Flores Zigzag Laranja",	"79.90"	,1	,sysdate(),	sysdate(),	"266"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Preto Liso X Costas",	"79.90"	,1	,sysdate(),	sysdate(),	"267"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Preto Liso X Decotao",	"79.90"	,1	,sysdate(),	sysdate(),	"268"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Liso Branco",	"79.90"	,1	,sysdate(),	sysdate(),	"269"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Drikis Branco Aberto Cintura",	"169.90"	,1	,sysdate(),	sysdate(),	"270"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Branco Renda Aberto Cintura Botões Na Frente",	"159.90"	,1	,sysdate(),	sysdate(),	"271"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Brancorenda Aberto Cintura Botões Na Frente",	"159.90"	,1	,sysdate(),	sysdate(),	"272"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Preta Renda De Decote V",	"149.90"	,1	,sysdate(),	sysdate(),	"273"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido De Alcinha Off Branca",	"89.90"	,1	,sysdate(),	sysdate(),	"274"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacao Fundo Branco Florido Laranja",	"119.90"	,1	,sysdate(),	sysdate(),	"275"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Renda Branca Cauda Atras",	"149.90"	,1	,sysdate(),	sysdate(),	"276"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Camurça Marrom Ziper",	"89.90"	,1	,sysdate(),	sysdate(),	"277"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Camurça Preta Ziper",	"89.90"	,1	,sysdate(),	sysdate(),	"278"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusinha Branca De Amarrar Nó",	"69.90"	,1	,sysdate(),	sysdate(),	"279"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Blusinha Rosa Com Flores Amarelas",	"59.90"	,1	,sysdate(),	sysdate(),	"280"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Kimono Fundo Preto Flores",	"99.90"	,1	,sysdate(),	sysdate(),	"281"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Kimono Fundo Verde Flores",	"99.90"	,1	,sysdate(),	sysdate(),	"282"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Kimono Fundo Rose Flores",	"99.90"	,1	,sysdate(),	sysdate(),	"283"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Kimono Fundo Off Flores",	"99.90"	,1	,sysdate(),	sysdate(),	"284"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Kimono Branco Liso",	"99.90"	,1	,sysdate(),	sysdate(),	"285"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body/Maio Rosa Conchas",	"79.90"	,1	,sysdate(),	sysdate(),	"286"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusinha Rosa Listrado Girassol De Amarrar Nó",	"69.90"	,1	,sysdate(),	sysdate(),	"287"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusinha Salmão De Amarrar Nó",	"69.90"	,1	,sysdate(),	sysdate(),	"288"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusinha Preta Branca Listrada Girassol De Amarrar Nó",	"69.90"	,1	,sysdate(),	sysdate(),	"289"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Blusinha Verde Girrassois De Amarrar Nó",	"69.90"	,1	,sysdate(),	sysdate(),	"290"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Jeans Botões Azul Escuro P",	"109.90"	,1	,sysdate(),	sysdate(),	"291"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Jeans Botões Azul Escuro M",	"109.90"	,1	,sysdate(),	sysdate(),	"292"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Saia Jeans Botões Azul Claro P E M",	"109.90"	,1	,sysdate(),	sysdate(),	"293"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Emcima Branco Fundo Listrado P",	"75.00"	,1	,sysdate(),	sysdate(),	"294A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Embaixobranco Fundo Listrado P",	"75.00"	,1	,sysdate(),	sysdate(),	"294B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Branco Listrado P",	"129.90"	,1	,sysdate(),	sysdate(),	"294C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Emcima Rosa Etnico M",	"75.00"	,1	,sysdate(),	sysdate(),	"295A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Embaixo Rosa Etnico M",	"75"	,1	,sysdate(),	sysdate(),	"295B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Rosa Etnico M",	"129.90"	,1	,sysdate(),	sysdate(),	"295C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Verde Etnico M",	"75.00"	,1	,sysdate(),	sysdate(),	"296A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Verde Etnico M",	"75.00"	,1	,sysdate(),	sysdate(),	"296B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Verde Etnico M",	"129.90"	,1	,sysdate(),	sysdate(),	"296C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Emcima Tropical G",	"75.00"	,1	,sysdate(),	sysdate(),	"297A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Tropical G",	"75.00"	,1	,sysdate(),	sysdate(),	"297B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Tropical G",	"129.90"	,1	,sysdate(),	sysdate(),	"297C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Ergometrico Preto M",	"75.00"	,1	,sysdate(),	sysdate(),	"298A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Embaixo Ergometrico Preto M",	"75.00"	,1	,sysdate(),	sysdate(),	"298B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Ergometrico Preto M",	"129.90"	,1	,sysdate(),	sysdate(),	"298C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Emcima Branco Ergometrico M",	"75.00"	,1	,sysdate(),	sysdate(),	"299A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Embaixo Branco Ergometrico M",	"75.00"	,1	,sysdate(),	sysdate(),	"299B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Branco Ergometrico M",	"129.90"	,1	,sysdate(),	sysdate(),	"299C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Laranja De Istras P",	"75.00"	,1	,sysdate(),	sysdate(),	"300A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Laranja De Istras P",	"75.00"	,1	,sysdate(),	sysdate(),	"300B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Laranja De Istras P",	"129.90"	,1	,sysdate(),	sysdate(),	"300C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Marimar Fundo Brancogg",	"75.00"	,1	,sysdate(),	sysdate(),	"301A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Marimar Fundo Branco Gg",	"75.00"	,1	,sysdate(),	sysdate(),	"301B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Marimar Fundo Branco Gg",	"129.90"	,1	,sysdate(),	sysdate(),	"301C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Emcima Salmão Renda M",	"75.00"	,1	,sysdate(),	sysdate(),	"302A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Salmão Renda M",	"75.00"	,1	,sysdate(),	sysdate(),	"302B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Salmão Renda M",	"129.90"	,1	,sysdate(),	sysdate(),	"302C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Emcima Pink Renda M",	"75.00"	,1	,sysdate(),	sysdate(),	"303A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Pink Renda M",	"75.00"	,1	,sysdate(),	sysdate(),	"303B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Bíquini Conjunto Pink Renda M",	"129.90"	,1	,sysdate(),	sysdate(),	"303C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Conjunto Floral Laranja Short Saia + Cropped",	"139.90"	,1	,sysdate(),	sysdate(),	"305"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Calça Floral Laranja Flare",	"79.90"	,1	,sysdate(),	sysdate(),	"306"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacao Fundo Azul Florzinhas Laranjas",	"119.90"	,1	,sysdate(),	sysdate(),	"307"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Saia Fundo Branco Palmeiras Flores",	"89.90"	,1	,sysdate(),	sysdate(),	"308"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macacão Fundo Branco Flores Laranjas Amarelo",	"119.90"	,1	,sysdate(),	sysdate(),	"309"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Babadinho Preto",	"69.90"	,1	,sysdate(),	sysdate(),	"310"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cinto Preto Fino Dupla Fivela Prata",	"69.90"	,1	,sysdate(),	sysdate(),	"311"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Liso Rosa Bebe",	"119.9"	,1	,sysdate(),	sysdate(),	"312"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Fundo Preto Orquidea",	"119.90"	,1	,sysdate(),	sysdate(),	"313"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Fundo Preto Mix Flores",	"119.90"	,1	,sysdate(),	sysdate(),	"314"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Fundo Verde Girassol",	"119.90"	,1	,sysdate(),	sysdate(),	"315"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Branco Liso Aberto Nas Costas",	"119.90"	,1	,sysdate(),	sysdate(),	"316"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Fundo Preto Colors",	"119.90"	,1	,sysdate(),	sysdate(),	"317"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Rosa Tropical",	"119.90"	,1	,sysdate(),	sysdate(),	"318"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Liso Pink Aberto Na Frente",	"119.90"	,1	,sysdate(),	sysdate(),	"319"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Branco Fundo Estampado",	"119.90"	,1	,sysdate(),	sysdate(),	"320"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Aberto Na Frente Preto De Girassois",	"119.90"	,1	,sysdate(),	sysdate(),	"321"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Preto Liso Aberto Na Frente",	"119.90"	,1	,sysdate(),	sysdate(),	"322"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Fundo Verde Folhas",	"119.90"	,1	,sysdate(),	sysdate(),	"323"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Macaquinho Aberto Nas Costa Preto Margarida",	"119.90"	,1	,sysdate(),	sysdate(),	"324"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Blusa Preta De Amarrar Aberto Em V Nas Costas",	"69.90"	,1	,sysdate(),	sysdate(),	"325"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Preto X Canelado",	"79.90"	,1	,sysdate(),	sysdate(),	"326"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Branco X Canelado",	"79.90"	,1	,sysdate(),	sysdate(),	"327"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Preto De Alcinha Canelado",	"79.90"	,1	,sysdate(),	sysdate(),	"328"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Vestido Marsala De Alcinha Canelado",	"79.90"	,1	,sysdate(),	sysdate(),	"329"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Preto Ilhos",	"89.90"	,1	,sysdate(),	sysdate(),	"330"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Off Ilhos",	"89.90"	,1	,sysdate(),	sysdate(),	"331"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Rosa Bebe Ilhos",	"89.90"	,1	,sysdate(),	sysdate(),	"332"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Short Envelope Preto",	"89.90"	,1	,sysdate(),	sysdate(),	"333"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Coloridos Alcinha",	"59.90"	,1	,sysdate(),	sysdate(),	"334"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Coloridos Manga Curta",	"69.90"	,1	,sysdate(),	sysdate(),	"335"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Cinza Canelado De Nó",	"69.90"	,1	,sysdate(),	sysdate(),	"336"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Cropped Cinza Canelado De Amarrar",	"69.90"	,1	,sysdate(),	sysdate(),	"337"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Body Tule Preto",	"99.90"	,1	,sysdate(),	sysdate(),	"338"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Camisetão Tule",	"99.90"	,1	,sysdate(),	sysdate(),	"339"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Floral Branco C/Tela G",	"129.90"	,1	,sysdate(),	sysdate(),	"340A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Floral Branco C/Tela G",	"75.00"	,1	,sysdate(),	sysdate(),	"340B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Floral Branco C/Tela G",	"75.00"	,1	,sysdate(),	sysdate(),	"340C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Azul Royal",	"129.90"	,1	,sysdate(),	sysdate(),	"341A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Azul Royal",	"75.00"	,1	,sysdate(),	sysdate(),	"341B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Azul Royal",	"75.00"	,1	,sysdate(),	sysdate(),	"341C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Azul Bordado C/Flores P",	"129.90"	,1	,sysdate(),	sysdate(),	"342A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Azul Bordado C/Flores Tiras P",	"75.00"	,1	,sysdate(),	sysdate(),	"342B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Azul Bordado C/Flores P",	"75.00"	,1	,sysdate(),	sysdate(),	"342C"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Emcima Floral Preto P",	"129.90"	,1	,sysdate(),	sysdate(),	"343A"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Embaixo Floral Preto P",	"75.00"	,1	,sysdate(),	sysdate(),	"343B"	);
insert into estoquepurchase.produtos(descricao,valor,fk_categoria,created_at,updated_at,codigo_produto) values(	"Biquini Conjunto Floral Preto P",	"75.00"	,1	,sysdate(),	sysdate(),	"343C"	);
